"""Lesson 1: Context Tracker - Example case scenarios by professional category.

Six categorized case scenarios demonstrating common context assembly patterns.
Students can paste these into the analyzer to see how it identifies
context gaps, assumptions, and coaching opportunities.
"""

EXAMPLE_CATEGORIES = [
    "Project Management",
    "Marketing",
    "Human Resources",
    "Finance",
    "Education",
    "Operations",
]

EXAMPLE_CONVERSATIONS = [
    {
        "category": "Project Management",
        "title": "Event planning without key constraints",
        "description": (
            "A project manager asks AI to help plan a company event without "
            "specifying budget, attendee count, or venue constraints. The AI "
            "produces an ambitious plan that is wildly out of scope. Once the "
            "PM adds concrete details, the plan becomes realistic and actionable."
        ),
        "raw_transcript": (
            "User: I need help planning our annual company event. Can you put "
            "together a plan?\n"
            "Assistant: Here is a comprehensive plan for your annual company event:\n\n"
            "1. Venue: Book a large convention center or luxury hotel ballroom\n"
            "2. Catering: Full-service catering with plated dinner, cocktail hour, "
            "and dessert station\n"
            "3. Entertainment: Hire a live band, set up a photo booth, and arrange "
            "a keynote speaker\n"
            "4. Activities: Team-building workshops, awards ceremony, raffle with "
            "premium prizes\n"
            "5. Logistics: Chartered buses for transportation, overnight hotel "
            "blocks for out-of-town staff\n\n"
            "Would you like me to break any of these sections down further?\n"
            "User: That is way too elaborate. We have a budget of $3,000 total, "
            "about 40 people, and we need to use our office conference room or a "
            "nearby park pavilion. It is a casual appreciation lunch, not a gala. "
            "Most people just want good food and a chance to relax together. We "
            "also have two employees with dietary restrictions: one is vegan and "
            "one has a nut allergy.\n"
            "Assistant: That changes things completely. Here is a realistic plan "
            "for a casual appreciation lunch for 40 people within $3,000:\n\n"
            "Venue: Your office conference room or the park pavilion. The pavilion "
            "is better for a relaxed atmosphere if weather permits. Reserve it as "
            "the primary option with the conference room as backup.\n\n"
            "Food ($1,800-2,200): Order from a local catering service that offers "
            "build-your-own taco or sandwich bars. These are crowd-pleasers that "
            "naturally accommodate dietary needs. Confirm vegan options and nut-free "
            "preparation with the caterer. Budget roughly $50 per person for food "
            "and beverages.\n\n"
            "Beverages ($200-300): Iced tea, lemonade, sparkling water, and coffee. "
            "Skip alcohol to keep costs down and avoid liability.\n\n"
            "Recognition ($200-300): Print personalized thank-you cards from "
            "leadership. Do a brief five-minute recognition moment, not a formal "
            "awards ceremony. People appreciate sincerity over production value.\n\n"
            "Extras ($200-400): A simple lawn game set if using the pavilion, or a "
            "playlist and a dessert table if indoors. A small raffle with gift cards "
            "in the $25-50 range adds fun without blowing the budget.\n\n"
            "Total estimated spend: $2,400-3,000. This keeps you within budget with "
            "a small cushion for unexpected costs."
        ),
    },
    {
        "category": "Marketing",
        "title": "Campaign messaging without audience details",
        "description": (
            "A marketer asks for campaign messaging without specifying the target "
            "audience, brand voice, or what makes the product different. The AI "
            "generates generic copy. After adding specifics about the audience and "
            "brand, the messaging becomes sharp and targeted."
        ),
        "raw_transcript": (
            "User: Write some marketing copy for our new product launch.\n"
            "Assistant: Here is some marketing copy for your product launch:\n\n"
            "Introducing our latest innovation! We are excited to bring you a "
            "groundbreaking new product that will transform the way you work. "
            "With cutting-edge features and unmatched quality, this is the solution "
            "you have been waiting for.\n\n"
            "Key benefits:\n"
            "- Save time and increase efficiency\n"
            "- Easy to use, no learning curve\n"
            "- Trusted by thousands of satisfied customers\n\n"
            "Order now and experience the difference!\n\n"
            "Would you like me to adjust the tone or focus?\n"
            "User: That is way too generic. Here is what you need to know: We "
            "are launching a meal planning subscription box called FreshPlate. Our "
            "target audience is working parents aged 30-45 who want to cook "
            "healthy dinners but have no time to plan meals or shop for ingredients. "
            "Our brand voice is warm, practical, and slightly humorous, like a "
            "helpful friend, not a salesperson. Our key differentiator is that every "
            "box includes 15-minute recipes designed by a pediatric nutritionist, "
            "so the meals are kid-approved and parent-friendly. Competitors focus "
            "on gourmet cooking; we focus on getting real food on the table fast.\n"
            "Assistant: Here is revised copy for FreshPlate:\n\n"
            "Headline: Dinner is figured out.\n\n"
            "You love your kids. You want them to eat real food. You also want to "
            "sit down before 9 PM. We get it.\n\n"
            "FreshPlate delivers pre-portioned ingredients and 15-minute recipes "
            "designed by a pediatric nutritionist. Every meal is tested on actual "
            "children, which means no hidden broccoli tricks needed.\n\n"
            "What makes FreshPlate different:\n"
            "- 15-minute recipes, start to table. Timed by real parents, not chefs.\n"
            "- Kid-approved flavors that adults genuinely enjoy too.\n"
            "- Designed by a pediatric nutritionist, so you skip the guilt.\n"
            "- No exotic ingredients you will never use again.\n\n"
            "Think of us as the friend who texts you 'just make this tonight' "
            "with a recipe that actually works.\n\n"
            "Try your first box for $29. Cancel anytime, because we are confident "
            "you will not want to."
        ),
    },
    {
        "category": "Human Resources",
        "title": "Performance improvement plan missing key details",
        "description": (
            "An HR professional asks for help writing a performance improvement "
            "plan without specifying the employee's role, what the performance "
            "gap is, or what conversations have already happened. The AI delivers "
            "a template response. With proper context, the plan becomes specific "
            "and legally sound."
        ),
        "raw_transcript": (
            "User: I need to write a performance improvement plan for an employee.\n"
            "Assistant: Here is a general performance improvement plan template:\n\n"
            "Performance Improvement Plan\n"
            "Employee Name: [Name]\n"
            "Date: [Date]\n"
            "Review Period: 30/60/90 days\n\n"
            "Areas Needing Improvement:\n"
            "1. [Describe performance gap]\n"
            "2. [Describe performance gap]\n\n"
            "Expected Standards:\n"
            "- [List expectations]\n\n"
            "Support Provided:\n"
            "- Additional training\n"
            "- Regular check-ins\n"
            "- Mentorship opportunity\n\n"
            "Would you like me to fill in any specific sections?\n"
            "User: I need something much more specific. The employee is a senior "
            "accounts receivable specialist who has been with us for four years. "
            "Over the last six months, her collections rate has dropped from 94 "
            "percent to 71 percent, and she has missed the monthly close deadline "
            "three times. I have had two informal conversations with her already: "
            "once in October when the pattern started, and again in December when "
            "it continued. She mentioned personal issues but did not share details. "
            "Our company policy requires a formal PIP after two documented verbal "
            "warnings. Her role requires maintaining at least an 85 percent "
            "collections rate and meeting all close deadlines.\n"
            "Assistant: Here is a specific PIP for your accounts receivable "
            "specialist:\n\n"
            "Performance Improvement Plan\n"
            "Position: Senior Accounts Receivable Specialist\n"
            "Review Period: 60 days (aligns with two full monthly close cycles)\n\n"
            "Background: Two documented verbal conversations were held on "
            "October 15 and December 10 regarding declining performance. This "
            "PIP formalizes the improvement expectations per company policy.\n\n"
            "Performance Gaps:\n"
            "1. Collections rate has declined from 94 percent to 71 percent over "
            "six months, which is below the 85 percent role requirement.\n"
            "2. Monthly close deadline was missed in October, November, and "
            "December 2025.\n\n"
            "Measurable Targets:\n"
            "- Achieve 80 percent collections rate by end of Month 1, and 85 "
            "percent by end of Month 2.\n"
            "- Meet all monthly close deadlines during the PIP period with zero "
            "misses.\n"
            "- Provide weekly aging report updates to the controller every Monday.\n\n"
            "Support Provided:\n"
            "- Weekly 30-minute check-ins with the manager to review progress.\n"
            "- Access to EAP resources if personal matters are contributing.\n"
            "- Refresher training on the collections prioritization workflow.\n\n"
            "Important: Document all check-ins in writing and have the employee "
            "sign the PIP acknowledgment. If she mentioned personal issues, ensure "
            "you reference EAP support without requiring her to disclose details. "
            "This protects both the employee and the company."
        ),
    },
    {
        "category": "Finance",
        "title": "Quarterly analysis without actual numbers",
        "description": (
            "A finance analyst asks AI to analyze quarterly results without "
            "providing the actual numbers, comparison period, or which metrics "
            "matter most. The AI can only give generic advice. Once the analyst "
            "provides real data and context, the analysis becomes substantive."
        ),
        "raw_transcript": (
            "User: Can you analyze our quarterly results and give me some insights?\n"
            "Assistant: I would be happy to help analyze your quarterly results. "
            "However, I need some data to work with. Could you provide:\n\n"
            "1. Revenue figures for this quarter and the comparison period\n"
            "2. Key expense categories and amounts\n"
            "3. Which metrics are most important to your stakeholders\n"
            "4. Any known factors that affected performance\n\n"
            "Without actual numbers, I can only suggest general areas to examine:\n"
            "- Revenue trends versus prior quarter and prior year\n"
            "- Margin analysis by product line or segment\n"
            "- Expense ratios compared to benchmarks\n"
            "- Cash flow patterns\n\n"
            "Share the specifics and I can provide a meaningful analysis.\n"
            "User: Good point. Here are our Q3 numbers: Revenue was $4.2M versus "
            "a plan of $4.8M, a shortfall of $600K. The miss was concentrated in "
            "our consulting services line, which came in at $1.1M versus $1.7M "
            "plan. Product revenue was actually $100K above plan at $3.1M. On "
            "expenses, we are $200K under budget because we held two open "
            "headcount positions unfilled. EBITDA came in at $380K versus $520K "
            "plan. The board cares most about revenue growth rate quarter over "
            "quarter and consulting pipeline health. Q2 total revenue was $4.0M.\n"
            "Assistant: Here is your Q3 analysis:\n\n"
            "Revenue: $4.2M actual versus $4.8M plan, a $600K shortfall of 12.5 "
            "percent. However, quarter-over-quarter growth was 5 percent ($4.0M "
            "to $4.2M), which is a positive signal for the board.\n\n"
            "The story is really two stories:\n"
            "- Product revenue outperformed plan by $100K, reaching $3.1M. This "
            "suggests strong market demand.\n"
            "- Consulting revenue missed by $600K ($1.1M vs $1.7M). This single "
            "line accounts for 100 percent of the revenue gap.\n\n"
            "For the board, frame it this way: total revenue grew 5 percent QoQ "
            "on the strength of product. The consulting miss is a capacity or "
            "pipeline issue, not a market issue. The two unfilled positions likely "
            "contributed directly to the consulting gap since you could not staff "
            "engagements.\n\n"
            "EBITDA of $380K versus $520K plan means margin compression of $140K. "
            "But $200K in expense savings from held headcount partially offset the "
            "revenue miss. Net impact to the bottom line was better than it could "
            "have been.\n\n"
            "Recommendation: The board presentation should lead with the 5 percent "
            "QoQ growth, then address consulting as a hiring and pipeline issue "
            "with a specific plan to fill those two roles in Q4."
        ),
    },
    {
        "category": "Education",
        "title": "Workshop design without audience or constraints",
        "description": (
            "An instructor asks AI to design a workshop without specifying "
            "audience skill level, time constraints, or learning objectives. The "
            "AI builds something that may be completely wrong for the audience. "
            "Once constraints are provided, the design becomes practical."
        ),
        "raw_transcript": (
            "User: Help me design a workshop on presentation skills.\n"
            "Assistant: Here is a comprehensive workshop on presentation skills:\n\n"
            "Workshop: Mastering Presentation Skills\n"
            "Duration: Full day (8 hours)\n\n"
            "Module 1 (2 hours): Foundations of Communication\n"
            "- History of rhetoric and persuasion\n"
            "- Communication theory models\n"
            "- Body language and nonverbal cues\n\n"
            "Module 2 (2 hours): Slide Design Principles\n"
            "- Visual hierarchy and typography\n"
            "- Color theory and accessibility\n"
            "- Advanced PowerPoint techniques\n\n"
            "Module 3 (2 hours): Delivery Techniques\n"
            "- Voice projection and pacing\n"
            "- Handling Q&A sessions\n"
            "- Managing stage fright\n\n"
            "Module 4 (2 hours): Practice and Feedback\n"
            "- Each participant delivers a 10-minute presentation\n"
            "- Peer and instructor feedback\n\n"
            "What aspect would you like me to develop further?\n"
            "User: That is way too much. I have a 90-minute lunch-and-learn slot "
            "for 15 mid-level managers who already present regularly but get "
            "feedback that their presentations are too long and unfocused. They "
            "do not need basics. They need a specific framework for tightening "
            "their message. One learning objective: every participant should leave "
            "with a method they can apply to their next presentation to cut it by "
            "30 percent without losing impact. No slides from me, this should be "
            "interactive. They will eat during the first 15 minutes.\n"
            "Assistant: Here is your 90-minute lunch-and-learn redesigned:\n\n"
            "Title: Say Less, Land More: Cutting Your Presentations by 30 Percent\n\n"
            "Minutes 0-15: Eating and Warm-Up\n"
            "While people eat, pose this question on a whiteboard: What is the "
            "longest presentation you have sat through that could have been an "
            "email? Let people call out answers. This builds energy without "
            "requiring full attention.\n\n"
            "Minutes 15-30: The 3-Layer Filter Framework\n"
            "Introduce a simple framework: for every slide or section, ask three "
            "questions. (1) Does my audience need this to make a decision? (2) "
            "Would anyone notice if I cut it? (3) Can this be a handout instead "
            "of a slide? Walk through one real before-and-after example using a "
            "generic status update deck.\n\n"
            "Minutes 30-55: Hands-On Cutting Exercise\n"
            "Pairs exercise. Each person pulls up a recent presentation on their "
            "laptop and applies the 3-Layer Filter with their partner. Goal: "
            "identify at least 30 percent of slides or talking points that can be "
            "cut or moved to backup. Partners hold each other accountable.\n\n"
            "Minutes 55-75: Share-Outs and Discussion\n"
            "Three or four pairs share what they cut and why. Facilitate a brief "
            "discussion on what was hardest to let go of and why.\n\n"
            "Minutes 75-90: Personal Commitment\n"
            "Each person writes on an index card: the specific presentation they "
            "will apply this to next, and one thing they will cut. Collect the "
            "cards and email them back in two weeks as a reminder.\n\n"
            "No slides from you needed. All you need is a whiteboard, index cards, "
            "and one printed before-and-after example to hand out."
        ),
    },
    {
        "category": "Operations",
        "title": "Process improvement without describing the current process",
        "description": (
            "An operations manager asks for process improvement recommendations "
            "without describing what the current process is, where the bottlenecks "
            "are, or what constraints exist. The AI gives textbook advice. With "
            "real process details, the recommendations become targeted."
        ),
        "raw_transcript": (
            "User: We need to improve our order fulfillment process. Any "
            "recommendations?\n"
            "Assistant: Here are some general recommendations for improving "
            "order fulfillment:\n\n"
            "1. Implement a warehouse management system for real-time inventory\n"
            "2. Optimize pick-and-pack workflows with batch processing\n"
            "3. Use barcode scanning to reduce errors\n"
            "4. Establish quality checkpoints before shipping\n"
            "5. Negotiate better carrier rates and offer multiple shipping options\n"
            "6. Track KPIs like order accuracy, fulfillment time, and return rate\n\n"
            "Would you like me to elaborate on any of these areas?\n"
            "User: Let me give you the real picture. We are a 12-person specialty "
            "food company shipping about 200 orders per week. Orders come through "
            "our Shopify store and are printed on paper in the morning. Our three "
            "warehouse staff pick orders from printed lists, but they often cross "
            "paths because there is no zone assignment. We average two to three "
            "wrong items per day, usually because handwriting on the pick lists is "
            "misread. Our biggest bottleneck is the afternoon shipping cutoff at "
            "3 PM. We regularly miss it for 10 to 15 orders because the packing "
            "station is a single table and only one person can pack at a time. We "
            "cannot invest in a full WMS system right now. Our budget for "
            "improvements is about $2,000.\n"
            "Assistant: Here are targeted recommendations for your situation:\n\n"
            "Problem 1: Wrong items from misread pick lists\n"
            "Fix: Stop printing handwritten lists. Export orders from Shopify as "
            "printed pick sheets with item SKUs, names, and bin locations in large "
            "clear font. This costs nothing and should eliminate most misreads "
            "immediately. If you want extra accuracy, add a simple barcode check "
            "using a $50 USB scanner and a free Shopify plugin.\n\n"
            "Problem 2: Pickers crossing paths\n"
            "Fix: Divide your warehouse into two zones. Assign one picker to each "
            "zone and have the third person float between zones and handle "
            "replenishment. Print pick sheets sorted by zone so each picker only "
            "works their area. This requires zero investment, just a floor plan "
            "sketch and 30 minutes of reorganization.\n\n"
            "Problem 3: Single packing station bottleneck before 3 PM\n"
            "Fix: Add a second packing station. You need a folding table ($80), "
            "a duplicate set of packing supplies ($150), and a second shipping "
            "label printer ($200-400). Pull the floating picker to the second "
            "station at 1 PM daily to clear the backlog before the 3 PM cutoff.\n\n"
            "Total estimated investment: $300-650, well within your $2,000 budget. "
            "Save the remaining budget for the barcode scanner and a small buffer "
            "stock of your top 10 most-shipped items to speed up picking.\n\n"
            "Start with the printed pick sheets tomorrow. That is zero cost and "
            "addresses your highest-frequency error immediately."
        ),
    },
]
